name: gadgetron
channels:
  - ismrmrd
  - gadgetron
  - nvidia/label/cuda-12.3.0
  - conda-forge
  - bioconda
  - defaults
  - intel
dependencies:
  - anaconda-client=1.11                  # dev
  - armadillo=9.900.5                     # dev
  - boost=1.80.0
  - breathe=4.34                          # dev
  - cmake=3.21.3                          # dev
  - conda-build=3.23                      # dev
  - conda-verify=3.1                      # dev
  - cuda-cudart                           # cuda
  - cuda-cudart-dev                       # cuda, dev
  - cuda-cccl                             # cuda
  - cuda-driver-dev                       # cuda, dev
  - cuda-libraries-dev                    # cuda, dev
  - cuda-libraries                        # cuda
  - cuda-runtime                          # cuda
  - cuda-nvcc                             # cuda, dev
  - cuda-nvrtc                            # cuda
  - cuda-nvrtc-dev                        # cuda, dev
  - dcmtk=3.6.1
  - deepdiff=5.8
  - doxygen=1.9                           # dev
  - fftw=3.3.9
  - gadgetron::gadgetron-python=1.4.1
  - gcc_linux-64=9.4.0                    # dev
  - gdb=11.1                              # dev
  - gmock=1.10.0                          # dev
  - gxx_linux-64=9.4.0                    # dev
  - gtest=1.10.0                          # dev
  - h5py=3.2.1
  - hdf5=1.10.6
  - howardhinnant_date=3.0.1              # dev
  - ismrmrd::ismrmrd=1.13.7
  - ismrmrd::ismrmrd-python>=1.9.8
  - junitparser=2.7.0
  - jupyter=1.0.0                         # dev
  - jq=1.6
  - libblas=*=*mkl
  - libcurl=7.79.1                        # dev
  - libxml2=2.9                           # dev
  - make=4.3                              # dev
  - matplotlib=3.4.3                      # dev
  - memkind=1.10.1
  - mkl>=2022.0.0
  - mkl-include>=2022.0.0                 # dev
  - ismrmrd::mrd-storage-server=0.0.12
  - ninja=1.10                            # dev
  - nlohmann_json=3.10.4                  # dev
  - numpy=1.22
  - onnxruntime=1.10.0
  - pyyaml=6.0                            # dev
  - pip=21.2.4                            # dev
  - packaging=21.3
  - plplot=5.15.0
  - pugixml=1.12.1
  - pyfftw=0.12.0
  - python=3.9
  - gadgetron::range-v3=0.11.0
  - recommonmark=0.7.1                    # dev
  - scipy=1.7.1
  - shellcheck=0.7.2                      # dev
  - ismrmrd::siemens_to_ismrmrd=1.2.11
  - sphinx=4.4.0                          # dev
  - sphinx_rtd_theme=0.4.3                # dev
  - sysroot_linux-64=2.17
  - valgrind=3.17                         # dev
  - xsdata>=22.2
  - yq=2.13                               # dev


