name: gadgetron
channels:
  - gadgetron
  - nvidia
  - conda-forge
  - bioconda
  - defaults
  - intel
  - cefca
dependencies:
  - anaconda-client=1.8.0
  - armadillo=9.900.5             # dev
  - boost=1.76.0
  - breathe=4.32.0                # dev
  - cmake=3.21.3                  # dev
  - cpr=1.7.2
  - conda-build=3.21.9            # dev
  - conda-verify=3.4.2            # dev
  - cuda-libraries-dev=11.6.1     # cuda, dev
  - cuda-libraries=11.6.1         # cuda
  - cuda-runtime=11.6.1           # cuda
  - cuda-nvcc=11.6.112            # cuda, dev
  - dcmtk=3.6.1
  - doxygen=1.9.2                 # dev
  - fftw=3.3.9
  - gadgetron-python=1.3.6
  - gcc_linux-64=9.4.0            # dev
  - gdb=11.1                      # dev
  - gmock=1.10.0                  # dev
  - gxx_linux-64=9.4.0            # dev
  - gtest=1.10.0                  # dev
  - h5py=3.2.1
  - hdf5=1.10.6
  - howardhinnant_date=3.0.1      # dev
  - ismrmrd=1.7.1
  - ismrmrd-python=1.9.8
  - jupyter=1.0.0                 # dev
  - jq=1.6
  - libblas=*=*mkl
  - libcurl=7.79.1                # dev
  - libxml2=2.9.12                # dev
  - libxslt=1.1.33                # dev
  - make=4.3                      # dev
  - matplotlib=3.4.3              # dev
  - memkind=1.10.1
  - mkl>=2022.0.0
  - mkl-include>=2022.0.0          # dev
  - mrd-storage-server=0.0.8
  - ninja=1.10.2                  # dev
  - nlohmann_json=3.10.4          # dev
  - numpy=1.22.1
  - onnxruntime=1.10.0
  - pyyaml=6.0                    # dev
  - pip=21.2.4                    # dev
  - packaging=21.3
  - plplot=5.11.2
  - pugixml=1.11.4                # dev
  - pyfftw=0.12.0
  - python=3.9.7
  - range-v3=0.11.0
  - recommonmark=0.7.1            # dev
  - scipy=1.7.1
  - siemens_to_ismrmrd=1.2.2
  - shellcheck=0.7.2              # dev
  - sphinx=4.4.0                  # dev
  - sphinx_rtd_theme=0.4.3        # dev
  - sysroot_linux-64=2.17
  - valgrind=3.17.0               # dev
  - xsdata=22.2
  - yq=2.13.0                     # dev
  - pip:
    - junitparser==2.2.0
